[10.0] [ADD] analytic_resource_plan
ForgeFlow/pmis pull request #22
Opened 2017-09-11 12:52 UTC by nikul-serpentcs

Analytic Resource Planning
==========================

An effective planning of the resources required for a project or analytic account becomes essential in organizations that are run by projects, or profit center accounting. The process of resource planning generally follows an rolling wave planning approach, in which the level of detail of the planned resources increases over time, as the details of the work required are known to the planning group.

Resources planned for a project/analytic account have an impact on the planned costs. If the resources are procured internally, the standard cost is determined. If the resources are procured externally, the user can indicate the supplier, and the planned costs are then determined on the basis of the supplier's price list.

Multiple planning versions can be maintained for a resource plan so that the organization can create a first rough-cut resource plan, that can then be refined as the project progresses.

2017-09-11 12:53 UTC, nikul-serpentcs commented
@aheficent Could you please review.

2017-09-18 12:10 UTC, AaronHForgeFlow requested changes
![image](https://user-images.githubusercontent.com/19620251/30541287-04ed2470-9c7b-11e7-86ed-8db24cc187fd.png)

Invalid field type in account_analytic_account

2017-09-18 13:33 UTC, aheficent commented on analytic_resource_plan/model/analytic_resource_plan.py
>          domain=[('type', '<>', 'view')],
The domain is still here @nikul-serpentcs

2017-09-19 04:26 UTC, nikul-serpentcs commented
@aheficent Removed domain, Could you please look it.

2017-09-20 14:38 UTC, AaronHForgeFlow requested changes
Can you add the form view for the resource plan lines? Is missing

2017-09-25 08:59 UTC, nikul-serpentcs commented
@aheficent Could you please look it.

2017-09-26 10:42 UTC, AaronHForgeFlow requested changes
There's a problem in the on_change method. Can make this module depend on analytic_schedule?

![image](https://user-images.githubusercontent.com/19620251/30856168-d424fc62-a2b7-11e7-8ee9-60e87d5b648c.png)

2017-09-27 06:02 UTC, nikul-serpentcs commented
@aheficent added 'analytic_schedule' in depends, Could you please look it.

2017-09-27 10:27 UTC, AaronHForgeFlow approved these changes
:+1:

2017-09-27 10:27 UTC, merged